# Generated by Django 3.0.2 on 2021-04-23 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emballage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('bl', 'blanc'), ('rg', 'rouge'), ('ble', 'bleur'), ('vr', 'vert'), ('muli', 'multicolore')], default='Transparent', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(default='Non definie')),
                ('prix', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Type', models.CharField(choices=[('em', 'emballe'), ('fr', 'frais'), ('cs', 'conserve')], max_length=2)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('emballag', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='magasin.Emballage')),
            ],
        ),
    ]
