# Generated by Django 3.0.2 on 2021-04-23 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0002_remove_produit_emballag'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='emballag',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='magasin.Emballage'),
        ),
    ]
