# Generated by Django 3.0.2 on 2021-04-23 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0005_produitnc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commander',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_garantie', models.CharField(max_length=100)),
                ('dateCde', models.DateField(default=datetime.date(2021, 4, 23), null=True)),
                ('totalCde', models.DecimalField(decimal_places=3, max_digits=10)),
                ('produits', models.ManyToManyField(to='magasin.Produit')),
            ],
        ),
    ]
