# Generated by Django 3.0.2 on 2021-05-30 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 20, 29, 41, 671274), max_length=50),
        ),
        migrations.AlterField(
            model_name='folder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 20, 29, 41, 671667)),
        ),
    ]
