# Generated by Django 3.0.2 on 2021-05-30 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_auto_20210530_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 21, 56, 5, 980451), max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to='cloudfiles'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 21, 56, 5, 980858)),
        ),
    ]
